{{- with .Values.appSpec.applications.netguard }}
  {{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-services-viewer-role
rules:
- apiGroups:
  - netguard.sgroups.io
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netguard.sgroups.io
  resources:
  - services/status
  verbs:
  - get
  {{- end }}
{{- end }}
