{{- with .Values.appSpec.applications.netguard }}
  {{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-addressgroupbindings-admin-role
rules:
- apiGroups:
  - netguard.sgroups.io
  resources:
  - addressgroupbindings
  verbs:
  - '*'
- apiGroups:
  - netguard.sgroups.io
  resources:
  - addressgroupbindings/status
  verbs:
  - get
  {{- end }}
{{- end }}
