{{- with .Values.appSpec.applications.netguard }}
  {{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $.Release.Name }}-{{ .name }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
{{- end }}
