{{- if .Values.appSpec.applications.web.enabled }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: breadcrumbs.in-cloud.io
spec:
  conversion:
    strategy: None
  group: in-cloud.io
  names:
    kind: Breadcrumb
    listKind: BreadcrumbList
    plural: breadcrumbs
    singular: breadcrumb
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
