{{- if .Values.appSpec.applications.web.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customformsprefills.front.in-cloud.io
spec:
  group: front.in-cloud.io
  names:
    kind: CustomFormsPrefill
    plural: customformsprefills
    singular: customformsprefill
    shortNames:
      - cfp
    listKind: CustomFormsPrefillList
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required: [overrideType, values]
              properties:
                overrideType:
                  type: string
                  description: "Fully qualified resource kind (e.g. in-cloud.io/v1alpha1/projects)"
                values:
                  type: array
                  description: "List of field path-value pairs to prefill in the form"
                  items:
                    type: object
                    required: [path, value]
                    properties:
                      path:
                        type: array
                        description: "JSON path as array of strings to target a field (e.g. ['spec', 'description'])"
                        items:
                          type: string
                      value:
                        description: "Prefilled value for the specified path"
                        x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}

{{- end }}
