{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "defaultNameSuffix" "config" "context" $) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  email_password: {{ .Values.email.password | b64enc | quote }}
  secret_key: {{ .Values.secretKey | default (randAscii 60) | b64enc | quote }}
  {{- range .Values.remoteAuth.backends }}
  {{- if eq . "netbox.authentication.LDAPBackend" }}
  ldap_bind_password: {{ $.Values.remoteAuth.ldap.bindPassword | b64enc | quote }}
  {{ end -}}
  {{ end -}}
{{- end -}}
