{{- with .Values.appSpec.applications.console }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-serving
  namespace: {{ $.Release.Namespace }}
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: issuer-selfsigned
  dnsNames:
  - {{ $.Release.Name }}-{{ .name }}
  - {{ $.Release.Name }}-{{ .name }}.{{ $.Release.Namespace }}
  - {{ $.Release.Name }}-{{ .name }}.{{ $.Release.Namespace }}.svc
  secretName: {{ $.Release.Name }}-serving-tls
  usages:
    - server auth
    - client auth
{{- end }}
