{{- range $appName, $appValue := .Values.applications }}
  {{- if $appValue.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-{{ $appValue.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "appSpec.labels" $ | nindent 4 }}
    {{- include "appSpec.applicationSelectorLabels" (list $appValue.name $) | nindent 4 }}
  {{- end }}
{{- end }}
