{{- with .Values.appSpec.applications.web }}
  {{- if .enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - {{ $.Release.Name }}.{{ $.Release.Namespace }}.{{ $.Values.domain }}
  gateways:
    - {{ $.Release.Name }}
  http:
    - name: {{ .name }}
      match:
        - uri:
            prefix: /client
      rewrite:
        uri: /client
      route:
        - destination:
            host: {{ $.Release.Name }}-{{ .name }}
            port:
              number: {{ .containers.web.extraPorts.ingress.containerPort }}

    - name: istio-ingress-redirect
      match:
        - uri:
            prefix: /
      redirect:
        uri: /client
        authority: {{ $.Release.Name }}.{{ $.Release.Namespace }}.{{ $.Values.domain }}

  {{- end }}
{{- end }}
