---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: instancekubernetesdeploys.instances.in-cloud.io
spec:
  group: instances.in-cloud.io
  names:
    kind: InstanceKubernetesDeploy
    listKind: InstanceKubernetesDeployList
    plural: instancekubernetesdeploys
    singular: instancekubernetesdeploy
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              instanceName:
                type: string
                description: Имя инстанса
              projectName:
                type: string
                description: Имя проекта
            required:
              - instanceName
              - projectName
