{{- with .Values.appSpec.applications.crossplane }}
  {{- if .enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-certmanager-ca
  namespace: {{ $.Release.Namespace }}
spec:
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ $.Release.Name }}-issuer-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 175200h
  renewBefore: 720h
  isCA: true
  literalSubject: "C=Earth, ST=Earth, L=Earth, O=Crossplane, CN=Crossplane"
  dnsNames:
  - crossplane-root-ca
  secretName: crossplane-certmanager-ca
  {{- end }}
{{- end }}
