{{- with .Values.appSpec.applications.crossplane }}
  {{- if .enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-{{ .volumes.serverCertificate.volume.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  secretName: {{ $.Release.Name }}-{{ .volumes.serverCertificate.volume.name }}
  isCA: false
  usages:
    - "server auth"
    - "client auth"
    - "signing"
    - "key encipherment"
  dnsNames:
  - "{{ $.Release.Name }}-crossplane"
  - "{{ $.Release.Name }}-crossplane.{{ $.Release.Namespace }}"
  - "{{ $.Release.Name }}-crossplane.{{ $.Release.Namespace }}.svc"
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  issuerRef:
    kind: Issuer
    name: {{ $.Release.Name }}-issuer
  {{- end }}
{{- end }}
