{{- with .Values.appSpec.applications.crossplane }}
  {{- if .enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-{{ .volumes.clientCertificate.volume.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: {{ $.Release.Name }}.{{ $.Release.Namespace }}
  secretName: {{ $.Release.Name }}-{{ .volumes.clientCertificate.volume.name }}
  usages:
    - "signing"
    - "key encipherment"
    - "client auth"
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  issuerRef:
    kind: Issuer
    name: {{ $.Release.Name }}-issuer
  {{- end }}
{{- end }}
