{{- with .Values.appSpec.applications.rbacmanager }}
  {{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-admin:main-resources
  labels:
    rbac.crossplane.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  verbs: 
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - "*"
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - pkg.crossplane.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - secrets.crossplane.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  {{- end }}
{{- end }}
