{{- with .Values.appSpec.applications.rbacmanager }}
  {{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-view:main-resources
  labels:
    rbac.crossplane.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pkg.crossplane.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.crossplane.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
  {{- end }}
{{- end }}
