{{- with .Values.appSpec.applications.rbacmanager }}
  {{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-browse:main-resources
  labels:
    rbac.crossplane.io/aggregate-to-browse: "true"
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
  {{- end }}
{{- end }}
