{{- with .Values.appSpec.applications.rbacmanager }}
  {{- if .enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-{{ .name }}:allowed-provider-permissions
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.crossplane.io/aggregate-to-allowed-provider-permissions: "true"
  {{- end }}
{{- end }}
