{{- with .Values.appSpec.applications.rbacmanager }}
  {{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Release.Name }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Release.Name }}-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $.Release.Name }}:masters
  {{- end }}
{{- end }}
