{{- with .Values.appSpec.applications.sgroupsprovider }}
  {{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-ieagagrules-admin-role
rules:
- apiGroups:
  - provider.sgroups.io
  resources:
  - ieagagrules
  verbs:
  - '*'
- apiGroups:
  - provider.sgroups.io
  resources:
  - ieagagrules/status
  verbs:
  - get
  {{- end }}
{{- end }}
