{{- with .Values.appSpec.applications.sgroupsprovider }}
  {{- if .enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ .volumes.controllerManagerConfig.volume.name }}
  namespace: {{ $.Release.Namespace }}
data:
  config.yaml: |
    app:
      name: 'sgroupsprovider-operator'
      version: '1.0.0'

    settings:
      sgroup_grpc_address: "{{ $.Values.sgroup.grpcAddress }}"

    logger:
      log_level: "{{ $.Values.sgroup.log_level }}"
  {{- end }}
{{- end }}
