cluster:
  name: cluster
  environment: test
  area: area
  index: 1

providerConfigs:
  kubernetes:
    apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: ProviderConfig
    metadata:
      name: kubernetes-provider-config
    spec:
      credentials:
        source: InjectedIdentity

environmentConfigs: {}
  # project-env:
  #   argocdToken: ""

kubernetes: {}
