{{- with .Values.appSpec.applications.ipamprovider }}
  {{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-networkclaims-admin-role
rules:
- apiGroups:
  - provider.sgroups.io
  resources:
  - networkclaims
  verbs:
  - '*'
- apiGroups:
  - provider.sgroups.io
  resources:
  - networkclaims/status
  verbs:
  - get
  {{- end }}
{{- end }}
