{{- if .Values.certificates.enabled }}

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  commonName: sgroups-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ .Release.Name }}-selfsigned
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: {{ .Release.Name }}-ca-secret

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Release.Name }}-ca-secret
{{- end }}
